parameters:
    env_name:
        type: string
        label: Environment name
    meta_groups:
        type: string
        label: Comma separataed list of metadata groups
        description: Groups used do manage ansible dynamic inventory
        default: "travis-UI"
    node_count:
        type: number
        label: Nodes Count
        description: Number of travis UI nodes
        default: 1
        constraints:
          - range: { min: 1 }
            description: Nodes Count must be at least 1
    node_flavor:
        type: string
        label: Node Instance Type
        description: Type of instance (flavor) to deploy for the travis node
        default: c2.large
        constraints:
          - custom_constraint: nova.flavor
    key_name:
        type: string
        label: Key Name
        description: SSH key to be used for all instances
        default: "Travis Master"
        constraints:
          - custom_constraint: nova.keypair
    image_name:
        type: string
        label: Image Name
        description: Image name to create node servers
        default: "Ubuntu 14.04"

resources:
  management_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Allow node management from internet (ICMP, SSH, HTTP, HTTPS, RabbitMQ, Management)
      name:
        str_replace:
          template: travis-%env_name%
          params:
            "%env_name%": { get_param: env_name }
      rules:
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: { get_param: api_port }
          port_range_max: { get_param: api_port }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 22, port_range_max: 22}
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: icmp }
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 80, port_range_max: 80}
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 443, port_range_max: 443}
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 4567, port_range_max: 4567}
        - { direction: ingress, remote_ip_prefix: 0.0.0.0/0, protocol: tcp, port_range_min: 8800, port_range_max: 8800}

  travis_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Full access between travis nodes in their environment
      name:
        str_replace:
          template: travis-%env_name%
          params:
            "%env_name%": { get_param: env_name }
      rules:
        # Allow all outgoing connections to Internet
        - { direction: egress, remote_ip_prefix: 0.0.0.0/0}
        # All all incoming connection from the same security group
        - { direction: ingress, remote_mode: remote_group_id }

  travis_servers:
      type: OS::Heat::ResourceGroup
      properties:
          count: { get_param: node_count }
          resource_def:
              type: OS::Nova::Server
              properties:
                name:
                    str_replace:
                        template: travis-%env_name%-n%index%
                        params:
                          "%env_name%": { get_param: env_name }
                image: { get_param: image_name }
                flavor: { get_param: node_flavor }
                key_name: { get_param: key_name }
                metadata:
                  groups: { get_param: meta_groups }
                networks:
                  - network: ext-net
                security_groups:
                  - {get_resource: management_security_group}
                  - {get_resource: travis_security_group}